<?php

return [
    'warn_about_relative_include_statement' => true,
    'processes' => 1,
    'directory_list' => [
        'src',
        'bin',
        'vendor',
    ],
    'exclude_analysis_directory_list' => [
        'vendor/'
    ],
    'skip_slow_php_options_warning' => false,
    'ignore_undeclared_functions_with_known_signatures' => false,
    'plugin_config' => [
        'php_native_syntax_check_max_processes' => 4,
        'has_phpdoc_method_ignore_regex' => '@^Phan\\\\Tests\\\\.*::(test.*|.*Provider)$@',
        'has_phpdoc_check_duplicates' => true,
        'empty_statement_list_ignore_todos' => true,
        'infer_pure_methods' => true,
        'regex_warn_if_newline_allowed_at_end' => true,
    ],
    'plugins' => [
        'AlwaysReturnPlugin',
        'DollarDollarPlugin',
        'UnreachableCodePlugin',
        'DuplicateArrayKeyPlugin',
        'PregRegexCheckerPlugin',
        'PrintfCheckerPlugin',
        'UseReturnValuePlugin',
        'UnknownElementTypePlugin',
        'DuplicateExpressionPlugin',
        'WhitespacePlugin',
        'InlineHTMLPlugin',
        'PHPDocToRealTypesPlugin',
        'PHPDocRedundantPlugin',
        'PreferNamespaceUsePlugin',
        'EmptyStatementListPlugin',
        'LoopVariableReusePlugin',
        'RedundantAssignmentPlugin',
        'StrictComparisonPlugin',
        'StrictLiteralComparisonPlugin',
        'ShortArrayPlugin',
        'SimplifyExpressionPlugin',
        'RemoveDebugStatementPlugin',
        'UnsafeCodePlugin',
        'DeprecateAliasPlugin',
    ],
];