name: PHP Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: xml json tokenizer ctype intl phpdbg phar mbstring
      - uses: actions/checkout@v3
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Cache PHIVE packages
        id: phive-cache
        uses: actions/cache@v3
        with:
          path: /home/runner/.phive/phars/
          key: ${{ runner.os }}-phive-${{ hashFiles('**/phars.xml') }}
          restore-keys: |
            ${{ runner.os }}-phive-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Install PHIVE tools
        uses: ngmy/phive-install-action@0.13.0
        with:
          phive-arguments: --force-accept-unsigned
      - name: Run php linting
        run: composer run-script phplint
      - name: Run psr12 linting
        # currently fails on readonly classes, which is a bug in the tool - remember to manually check the result
        run: composer run-script psr12lint || true
      - name: Run requirements checker
        run: composer run-script requirement
      - name: Run mess detector
        # currently fails on readonly classes, which is a bug in the tool - remember to manually check the result
        run: composer run-script mess || true
      - name: Run unit tests
        run: composer run-script test
      - name: Run mutation tests
        run: composer run-script infection
      - name: Run self test
        run: php bin/estimate-cost
